### ISSUE TITLE
Subtle issue with normalizing URIs 

### ISSUE THREAD

**Issue by benlovell** [httprb/http.rb#206]
Since 81509bc we've had issues with using this gem to communicate with elasticsearch. It seems that prior to this change, the request URI was being normalized correctly and thus not including the scheme and host segment. As is evidenced below:

![screen shot 2015-04-07 at 11 25 17](https://cloud.githubusercontent.com/assets/41963/7021404/05c4417c-dd19-11e4-9766-a86a9a587b61.png)

And after 81509bc:

![screen shot 2015-04-07 at 11 26 07](https://cloud.githubusercontent.com/assets/41963/7021411/16f869fa-dd19-11e4-97e7-d8b1b89d4e55.png)

It seems some servers are strict in this regard. Elasticsearch apparently being one of them. :see_no_evil: 

This is easily resolved by `uri.normalize.request_uri` instead of just normalizing the URI, but this causes some issues with proxying that I don't really understand.

**Comment by ixti** [comment]
Thanks for report. My bad. Will fix today.

**Comment by ixti** [comment]
It should not send `schema://hostname` inside `METHOD ...` line.

**Comment by ixti** [comment]
Actually I have misunderstood original code and wiped out things that were essential. Will provide a fix ASAP.

**Comment by ixti** [comment]
Released as `0.8.3`.

**Comment by benlovell** [comment]
:heart:

**Comment by britishtea** [comment]
I ran into an issue today due to this commit.

I often use Charles Proxy to inspect HTTP(S) requests. When proxying HTTPS request to , for example, https://www.google.com, I see requests being made to `https://www.google.comhttps://www.google.com/`. I suspect this is due to the headline, which is `"GET https://google.com/ HTTP/1.1"`.

The following code causes the problem:

```ruby
require "http"

HTTP.via("0.0.0.0", 8888).get "https://www.google.com", :ssl => { :verify_mode => OpenSSL::SSL::VERIFY_NONE }
```

When doing the same thing with a persistent connection to http://www.google.com (plain HTTP) everything works as expected. The headline is `"GET / HTTP/1.1"` in that case.

Is `http` doing the correct thing here? I've not had such issues with other ruby libraries when proxying HTTPS requests.

**Comment by tarcieri** [comment]
@britishtea definitely seems like a bug, possibly related to Addressable?

**Comment by ixti** [comment]
@Connorhd fixed issue reported by @britishtea in https://github.com/httprb/http/commit/2625436bb25ab779e79b4b1ad6f2df9f94e43e48
